name: deployment-job

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: Type in the deployment environment
        type: string
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run somthing
        run: echo "${{ inputs.environment }}"